name = "MyBlog"
license = "MIT"
licenselink = "https://github.com/wisnuwiry/hugo-personal-site/blob/master/LICENSE"
description = "Hugo theme for Personal Site, and Portfolio"
homepage = "https://wisnuwiry.space"
tags = [
  "blog",
  "clean",
  "responsive",
  "minimal",
  "clean",
  "light",
  "dark",
  "personal",
  "portfolio",
  "fast",
  "modern",
  "netlify",
  "seo",
  "dark mode",
  "website",
  "contact",
  "professional"
]
features = [
  "seo",
  "dynamic theme",
  "opengraph",
  "widgets",
  "json-ld",
  "forestry",
  "blog",
  "project",
  "contact",
  "about"
]
min_version = "0.41.0"

[author]
  name = "Wisnu G. Saputra"
  homepage = "https://wisnuwiry.space"
